THREADS: 32
SAMPLE: ["Tanz-1_deepsignalDNAmeth_unkb"]
FEATURES:
      chrName: [
                "Chr1_Chr2_Chr3_Chr4_Chr5",
#                "Chr1"
                "Chr2",
                "Chr3",
                "Chr4",
                "Chr5"
               ]
MAPPING:
      reference: "data/index/Tanz-1.patch.scaffold.Chr"
COVERAGE:
      regionBodyLength: 2000
      startLabel: "Start"
      endLabel: "End"
      upstream: 2000
      downstream: 2000
      flankName: "2kb"
      binSize: 10
      binName: "10bp"
      sortRegions: "keep"
